
###
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Nvidia",
  "price": 1000,
  "symbol": "NVDA",
  "image": "NVDA.png"
}



###
POST http://localhost:3000/assets
Content-Type: application/json

[
  {
  "name": "Amazon",
  "price": 100,
  "symbol": "AMZN",
  "image": "AMZN.png"
  },
  {
  "name": "Sales Force",
  "price": 200,
  "symbol": "CRM",
  "image": "CRM.png"
  },
  {
    "name": "Google",
    "price": 320,
    "symbol": "GOOGL",
    "image": "GOOGL.png"
  },
  {
    "name": "Coca-Cola",
    "price": 700,
    "symbol": "KO",
    "image": "KO.png"
  },
  {
    "name": "McDonalds",
    "price": 450,
    "symbol": "MCD",
    "image": "MCD.png"
  },
  {
    "name": "Mercado Livre",
    "price": 550,
    "symbol": "MELI",
    "image": "MELI.png"
  },
  {
    "name": "Meta",
    "price": 850,
    "symbol": "META",
    "image": "META.png"
  }
]

###
@assetId = {{ createAsset.response.body._id }}
@assetSymbol = {{ createAsset.response.body.symbol }}

###
GET http://localhost:3000/assets

###

GET http://localhost:3000/assets/{{ assetSymbol }}

###
# @name createWallet
POST http://localhost:3000/wallets

###
@walletId = {{ createWallet.response.body._id }}

###
GET http://localhost:3000/wallets

###

GET http://localhost:3000/wallets/bf7b12d3-3c62-495e-9929-bf475ef5cd0c


###
POST http://localhost:3000/wallets/{{ walletId }}/assets
Content-Type: application/json

{
  "assetId": "{{ assetId }}",
  "shares": 10
}

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "walletId": "{{ walletId }}",
  "assetId": "{{ assetId }}",
  "shares": 10,
  "price": 100,
  "type": "BUY"
}

###
GET http://localhost:3000/orders?walletId={{ walletId }}
